version: "3.8"
   
services:
  db:
    image: postgres
    env_file:
      - .postgres
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - .env
      - .postgres
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    build : ./nginx
    volumes :
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - django